#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'jumpingOnClouds' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY c as parameter.
#

def jumpingOnClouds(c):
    # Write your code here
    jump = 0
    i = 0
    while(len(c) > 1):
        print(len(c))
        if len(c) == 2:
            jump += 1
            c.pop(0)
        if len(c) > 2:
            if c[1] == 0:
                if c[2] == 0:
                    print(c[0])
                    print(c[1])
                    print(c[2])
                    jump += 1
                    c.pop(0)
                    c.pop(0)
                    print("2 zeros jumped")
                    print(c)
                elif c[2] == 1:
                    print(c[0])
                    print(c[1])
                    print(c[2])
                    jump += 1
                    c.pop(0)
                    print("1 zero jumped")
                    print(c)
            elif c[1] == 1:
                print(c[i])
                print(c[1])
                print(c[2])
                jump += 1
                c.pop(0)
                c.pop(0)
                print("one jumped")
                print(c)
            else:
                print("mistake")
    return jump
        
        
    
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    c = list(map(int, input().rstrip().split()))

    result = jumpingOnClouds(c)

    fptr.write(str(result) + '\n')

    fptr.close()
